on:
  push:
    branches:
      - matrix

jobs:
  explicit:
    strategy:
      matrix:
        os:
          - windows-2022  # windows-latest
          - windows-2019
          - ubuntu-22.04  # ubuntu-latest
          - ubuntu-20.04
          - macos-12  # macos-latest
          - macos-11
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        include:
          - os: ubuntu-22.04
            python-version: "3.7"
          - os: ubuntu-22.04
            python-version: "3.11"
        exclude:
          - os: macos-12
            python-version: "3.8"
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Showcase Python shell
        shell: python
        run: |
          import platform
          import sys

          print(platform.platform())
          print(sys.executable)
          print(sys.version_info)