on:
  push:
    branches:
      - python-shell

jobs:
  ci:
    strategy:
      matrix:
        os:
          - windows-2022  # windows-latest
          - windows-2019
          - ubuntu-22.04  # ubuntu-latest
          - ubuntu-20.04
          - macos-12  # macos-latest
          - macos-11
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      name: Showcase Python shell
      shell: python
      run: |
        import platform
        import sys
        
        print(platform.platform())
        print(sys.executable)
        print(sys.version_info)
        
        import pip